### ISSUE TITLE
`read_all` for reading everything available on the socket without blocking

### ISSUE THREAD

**Issue by rushmorem** [withoutboats/romio#59]
Is it possible to read everything available on the socket (`TcpStream` actually) in one atomic read like `read` does but without requiring a fixed buffer? I know we have `read_to_end` but it keeps waiting for more data. If it's possible at all and this is something you would like to have as part of this library, I will be glad to send a pull request if someone can point me in the right direction.

**Comment by kpp** [comment]
That's where you should start from https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-util/src/io/read.rs#L27 and https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-io/src/lib.rs#L112

I am not sure `romio` should handle this issue since all io operations came from tokio -> futures-util  and imported as-is in romio.

**Comment by rushmorem** [comment]
You are right. I should have opened this on the `futures` repo. Thanks.
