### ISSUE TITLE
what is the state of library?

### ISSUE THREAD

**Issue by luover** [withoutboats/romio#60]
Now , The new [RFC#2592] (https://github.com/rust-lang/rfcs/pull/2592) like remove LocalWaker,  so This library will update? also why this [PR](https://github.com/withoutboats/romio/pull/7) is stop.

Is this library active?

**Comment by yoshuawuyts** [comment]
@luover Romio is pretty stable as it is. It aims to be a reference / baseline implementation of a reactor; essentially being a Futures layer on top of `mio`.

`tokio-timer` wasn't ported because it relies on a large custom timer implementation instead of calling out to the system timers. We should probably open an issue + PR to create bindings to system timers.

**Comment by yoshuawuyts** [comment]
The waker change just came through, and it's landed in #66. I hope you feel your questions have been answered. Thanks!
